libxml: update the version number to 2.9.0 to match the upgrade in poky
upgrade the version to 2.9.0 to fix following version mismatch issue:
ERROR: No recipes available for:
  /srv/home/pokybuild/yocto-autobuilder/yocto-slave/p1022ds/build/yocto/meta-fsl-ppc/recipes-append/libxml/libxml2_2.8.0.bbappend

[YOCTO #3476]

Signed-off-by: Zhenhua Luo <b19537@freescale.com>