l2switch: follow Yocto packaging rules
Current so link packaging rule breaks the Yocto policy, correct it.

Fixed following error:
ERROR: QA Issue: non -dev/-dbg/-nativesdk package contains symlink .so:
l2switch-lib path '.../packages-split/l2switch-lib/usr/lib/libvtss_api.so'
ERROR: QA run found fatal errors. Please consider fixing them.

Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>